[mail]
version = V4.0.1
#SMTP服务器
smtp_server = smtphz.qiye.163.com
#发件人邮箱
sender_email = bioinfo@biosan.cn
#发件人邮箱密码
password = BioSan@17.
#郑州大学第三附属医院收件邮箱列表，邮箱间以", "分隔
receiver_zdfs = zdsfyczfzyc@163.com
#郑州大学第三附属医院邮件抄送邮箱列表，邮箱间以", "分隔
receiver_zdfs_acc = fanmingduo@biosan.cn, zhuyuanyuan@biosan.cn, lijunjie@biosan.cn
#北京协和吴老师收件邮箱列表，邮箱间以", "分隔
receiver_bjxh = Guozhuang_Li@outlook.com, zhaosen830@163.com
#北京协和吴老师邮件抄送邮箱列表，邮箱间以", "分隔
receiver_bjxh_acc = xukexin23@outlook.com, qing.li1994@outlook.com, support@imperialgene.com, hanmingya@biosan.cn, haomeirong@biosan.cn, hanjingjing@biosan.cn
#北京协和吴老师数据上传失败时收件邮箱列表，邮箱间以", "分隔
receiver_bjxh_fail = hanjingjing@biosan.cn
#上海新华医院上海市儿科研究所收件邮箱列表，邮箱间以", "分隔
receiver_shhc = zhuyuanyuan@biosan.cn, renmengyuan@biosan.cn, zhangzhaoxin@biosan.cn
#上海新华医院上海市儿科研究所邮件抄送邮箱列表，邮箱间以", "分隔
receiver_shhc_acc = hanjingjing@biosan.cn
#流程运行完成提醒人员邮箱，邮箱间以", "分隔
receiver_alerts = haomeirong@biosan.cn, hanjingjing@biosan.cn
#山东山大附属生殖医院有限公司收件邮箱列表，邮箱间以", "分隔
receiver_sdsz = 17863803412@163.com
#北京金域医学检验实验室有限公司收件邮箱列表，邮箱间以", "分隔
receiver_bkw = linzhe1@biosan.cn
#北京金域医学检验实验室有限公司邮件抄送邮箱列表，邮箱间以", "分隔
receiver_bkw_acc = hanjingjing@biosan.cn, chenxiangjian@biosan.cn
