"""Actual bs7 wheel-generated bytes; synthetic terminal is not live authority."""
import hashlib
import json
import os
from pathlib import Path

import pytest

from app.cce_recovery_evidence import validate_recovery_evidence
from scripts.cce_recovery_inventory import validate_submission_inventory


SOURCE = "25297f971dd463176d5fdc07908a60095ade50ea"
WHEEL = "2ad4aa737e6f34930b6832e3ce69edd9ee64867cc9c7ce0c1bcb4c455cdbae86"
CHECKSUMS = "de1b3ab20d888f9660c38b8dce037333ce3ce3b0b81b66fbf79563832b780296"
PROVENANCE = "74102da1e10cab3728bed6f1caf31eb4bf1a0d08ed42c6002b01d1048041f83f"
FILES = ("context.json", "submit-events.ndjson", "journal-state.json",
         "executor-control-failure.json", "jobs.ndjson")


@pytest.mark.parametrize("scope", ["wgs-get-lease", "wgs-list-pod", "gatk-get-lease", "gatk-list-pod"])
def test_actual_bs7_control_evidence_preserves_admitted_worker_and_requires_terminal(scope):
    root = os.environ.get("CCE_BS7_FIXTURE_ROOT")
    if not root:
        pytest.skip("requires pinned actual bs7 producer fixtures")
    root = Path(root)
    assert hashlib.sha256(Path("/bs7.whl").read_bytes()).hexdigest() == WHEEL
    provenance_bytes = (root / "fixture-provenance.json").read_bytes()
    assert hashlib.sha256(provenance_bytes).hexdigest() == PROVENANCE
    provenance = json.loads(provenance_bytes)
    assert provenance["source_commit"] == SOURCE
    assert provenance["wheel_sha256"] == WHEEL
    assert provenance["terminal_seal_produced"] is False
    checksums_bytes = (root / "SHA256SUMS").read_bytes()
    assert hashlib.sha256(checksums_bytes).hexdigest() == CHECKSUMS
    checksums = {}
    for line in checksums_bytes.decode("ascii").splitlines():
        digest, name = line.split("  ", 1)
        assert name not in checksums
        checksums[name] = digest
    raw = {name: (root / scope / name).read_bytes() for name in FILES}
    for name, content in raw.items():
        assert hashlib.sha256(content).hexdigest() == checksums[f"{scope}/{name}"]
    context, candidate = (json.loads(raw[name]) for name in (FILES[0], FILES[3]))
    rows = [json.loads(line) for line in raw[FILES[1]].splitlines()]
    expected_outcome = "CREATED" if scope.endswith("get-lease") else "ADOPTED"
    assert [row["event"] for row in rows] == ["INTENT", "CREATE_REQUESTED", expected_outcome]
    assert context["pipeline"] == scope.split("-")[0]
    assert candidate["failures"][0]["worker_uid"] == "worker-uid"
    assert candidate["failures"][0]["creation_state"] == "UNKNOWN"
    inventory = validate_submission_inventory(expected_context=context,
        journal_bytes=raw[FILES[1]], checkpoint_bytes=raw[FILES[2]],
        candidate_bytes=raw[FILES[3]], manifest_bytes=raw[FILES[4]])
    assert inventory["workers"] == [{"name": f"snakejob-synthetic-{scope}", "uid": "worker-uid"}]
    assert inventory["executor_failure_count"] == 1
    assert "sealed" not in inventory
    with pytest.raises(ValueError):
        validate_recovery_evidence(expected_context=context, candidate=candidate, terminal=None)
    # Explicit test-only complete terminal scaffolding; NOT producer evidence.
    digest = hashlib.sha256(json.dumps(candidate, sort_keys=True, separators=(",", ":"),
        ensure_ascii=False, allow_nan=False).encode()).hexdigest()
    terminal = dict(context, schema="cce.master-terminal.v1", sealed=True, complete=True,
        plugin_failure_sha256=digest, worker_inventory_complete=True,
        worker_ownership_verified=True, submissions_reconciled=True,
        master_state="failed", master_pod_state="terminated", exit_code=1,
        fatal_source="executor_control", executor_failure_count=1, rule_failure_count=0,
        other_failure_count=0, active_worker_jobs=0, active_worker_pods=0, unresolved_submissions=0)
    result = validate_recovery_evidence(expected_context=context, candidate=candidate, terminal=terminal)
    assert result["category"] == "heavy_slot_api_unavailable"
    assert result["source_execution_id"] == context["execution_id"]
    assert "automatic_recovery_allowed" not in result
