"""Opt-in cross-repository producer contract, not a real Master acceptance.

The fixture root is a read-only mount of files generated by the actual candidate
plugin under a synthetic API. Never rewrite producer files to make them pass.
The terminal below is deliberately synthetic, not runtime authorization.
"""
import hashlib
import json
import os
from pathlib import Path

import pytest

from app.cce_recovery_evidence import validate_recovery_evidence


# Original bytes from plugin commit 0d60648922b27aee25eda3ea7900f50467fbe0d9,
# candidate wheel 0.6.4+biosan4.p0.1; provenance is retained in HANDOFF.md.
FIXTURE_SHA256 = {
    "wgs": ("b931e3896727a2d83e5bb2c4ed48ffd562ad7f59b6018f3ad854690d409bcbbe",
            "baacfb34fa37b7e9494bbc760c8a1296683e3458770f95ecf72a5bdb5549b6ff"),
    "gatk": ("f6c085b214389c43622f818cdf355906151a8086a8500b02e44b51980f448c91",
             "17f49f7db149adeb733b33cfdc5d3e8cf8438afd838f5ac5daed4a7781d5775f"),
}


@pytest.fixture(params=["wgs", "gatk"])
def producer(request):
    root = os.environ.get("CCE_PRODUCER_FIXTURE_ROOT")
    if not root:
        pytest.skip("requires the pinned external candidate producer fixture")
    scope = Path(root) / (request.param + "-admission")
    context_bytes = (scope / "submit-context.json").read_bytes()
    candidate_bytes = (scope / "executor-failure.json").read_bytes()
    assert (hashlib.sha256(context_bytes).hexdigest(),
            hashlib.sha256(candidate_bytes).hexdigest()) == FIXTURE_SHA256[request.param]
    context = json.loads(context_bytes)
    candidate = json.loads(candidate_bytes)
    assert context["pipeline"] == candidate["pipeline"] == request.param
    assert candidate["automatic_recovery_allowed"] is False
    assert candidate["requires_master_terminal"] is True
    return context, candidate


def test_actual_candidate_alone_cannot_authorize_recovery(producer):
    context, candidate = producer
    with pytest.raises(ValueError, match="schema"):
        validate_recovery_evidence(expected_context=context, candidate=candidate, terminal=None)


def test_actual_admission_candidate_with_synthetic_terminal_contract(producer):
    context, candidate = producer
    digest = hashlib.sha256(json.dumps(candidate, sort_keys=True, separators=(",", ":"),
        ensure_ascii=False, allow_nan=False).encode("utf-8")).hexdigest()
    terminal = dict(context, schema="cce.master-terminal.v1",
        plugin_failure_sha256=digest, sealed=True, complete=True,
        worker_inventory_complete=True, worker_ownership_verified=True,
        submissions_reconciled=True, master_state="failed", master_pod_state="terminated",
        exit_code=1, fatal_source="executor_submission", executor_failure_count=len(candidate["failures"]),
        rule_failure_count=0, other_failure_count=0, active_worker_jobs=0,
        active_worker_pods=0, unresolved_submissions=0)
    result = validate_recovery_evidence(expected_context=context, candidate=candidate, terminal=terminal)
    assert result["category"] == "worker_create_admission_timeout"
    assert result["source_execution_id"] == context["execution_id"]
    assert result["source_master_uid"] == context["master_job_uid"]
