from __future__ import annotations

import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Dict, Iterable, List, Sequence

import pandas as pd


BATCH_PATTERN = re.compile(r"^\d{8}[A-Z]$")
REANALYSIS_SUFFIX = re.compile(r"R\d+$")


def parse_batches(value: str) -> List[str]:
    batches: List[str] = []
    for item in str(value).split(","):
        batch = item.strip()
        if not batch:
            continue
        if not BATCH_PATTERN.fullmatch(batch):
            raise ValueError(f"批次格式错误，必须是8位数字加1位大写字母: {batch}")
        if batch not in batches:
            batches.append(batch)
    if not batches:
        raise ValueError("--batch 至少需要一个有效批次")
    return batches


def read_reanalysis_samples(path: Path | str) -> pd.DataFrame:
    source = Path(path).expanduser().resolve()
    if not source.is_file():
        raise FileNotFoundError(f"重分析 samplelist 不存在: {source}")
    rows: List[Dict[str, str]] = []
    seen: Dict[str, str] = {}
    with source.open("r", encoding="utf-8-sig") as handle:
        for line_number, line in enumerate(handle, start=1):
            text = line.strip()
            if not text or text.startswith("#"):
                continue
            fields = [field.strip() for field in text.split(",")]
            if len(fields) != 2 or not all(fields):
                raise ValueError(
                    f"重分析 samplelist 第 {line_number} 行必须为两列：样本编号,上机批次；实际为：{text}"
                )
            sample_id, batch = fields
            if any(char.isspace() for char in sample_id):
                raise ValueError(f"重分析 samplelist 第 {line_number} 行样本编号包含空白字符：{sample_id}")
            if not BATCH_PATTERN.fullmatch(batch):
                raise ValueError(
                    f"重分析 samplelist 第 {line_number} 行上机批次格式错误，必须是8位数字加1位大写字母：{batch}"
                )
            if sample_id in seen and seen[sample_id] != batch:
                raise ValueError(
                    f"重分析 samplelist 中样本 {sample_id} 对应多个上机批次：{seen[sample_id]},{batch}"
                )
            if sample_id not in seen:
                seen[sample_id] = batch
                rows.append({"sampleId": sample_id, "batchNo": batch})
    if not rows:
        raise ValueError(f"重分析 samplelist 没有有效的样本编号和上机批次: {source}")
    return pd.DataFrame(rows, columns=["sampleId", "batchNo"])


def raw_sample_id(analysis_sample_id: str) -> str:
    """Only remove the suffix generated by this prepare module."""
    return REANALYSIS_SUFFIX.sub("", str(analysis_sample_id).strip())


def read_samplelist(path: Path | str) -> pd.DataFrame:
    source = Path(path)
    try:
        frame = pd.read_csv(source, sep="\t", dtype=str, keep_default_na=False).fillna("")
    except pd.errors.ParserError as exc:
        raise ValueError(f"Samplelist 格式错误: {source}: {exc}") from exc
    required = {"batchNo", "sampleId"}
    missing = sorted(required - set(frame.columns))
    if missing:
        raise ValueError(f"Samplelist 缺少列 {','.join(missing)}: {source}")
    frame["_samplelist_file"] = str(source.resolve())
    return frame


def find_batch_samplelists(directory: Path | str, batch: str, filename_glob: str) -> List[Path]:
    root = Path(directory).expanduser().resolve()
    pattern = filename_glob.format(date=batch[:8], batch=batch)
    return sorted(path for path in root.glob(pattern) if path.is_file())


def load_batch_samples(
    directory: Path | str,
    batches: Sequence[str],
    platform: str,
    filename_glob: str,
    panel: str,
    excluded_project_codes: Iterable[str],
) -> pd.DataFrame:
    frames: List[pd.DataFrame] = []
    excluded = set(excluded_project_codes)
    for batch in batches:
        paths = find_batch_samplelists(directory, batch, filename_glob)
        if not paths:
            raise FileNotFoundError(f"在 {Path(directory).expanduser()} 中未找到批次 {batch} 的 Samplelist")
        found = False
        for path in paths:
            frame = read_samplelist(path)
            frame = frame[frame["batchNo"].astype(str).str.strip() == batch]
            if "techPlatformCode" in frame.columns:
                frame = frame[frame["techPlatformCode"].astype(str).str.strip() == platform]
            if "itemCode" in frame.columns:
                frame = frame[frame["itemCode"].astype(str).str.strip() == panel]
            if "projectCode" in frame.columns:
                frame = frame[~frame["projectCode"].isin(excluded)]
            if not frame.empty:
                found = True
                frames.append(frame)
        if not found:
            raise ValueError(f"批次 {batch} 中没有符合平台 {platform} 和项目 {panel} 的样本")
    merged = pd.concat(frames, ignore_index=True).fillna("")
    return merged.drop_duplicates(subset=["batchNo", "sampleId"], keep="first")


class SamplelistRepository:
    def __init__(self, directory: Path | str, filename_glob: str = "Samplelist_*.txt"):
        self.directory = Path(directory).expanduser().resolve()
        self.filename_glob = filename_glob
        self._cache: Dict[Path, pd.DataFrame] = {}

    def _paths(self, batch: str = "") -> List[Path]:
        if not batch:
            raise ValueError("Samplelist 查找必须提供上机批次")
        pattern = self.filename_glob.format(date=batch[:8], batch=batch)
        return sorted((path for path in self.directory.glob(pattern) if path.is_file()), reverse=True)

    def _read(self, path: Path) -> pd.DataFrame:
        if path not in self._cache:
            self._cache[path] = read_samplelist(path)
        return self._cache[path]

    def find(self, sample_id: str, batch: str = "") -> Dict[str, str] | None:
        candidates: List[Dict[str, str]] = []
        for path in self._paths(batch):
            frame = self._read(path)
            matched = frame[frame["sampleId"].astype(str).str.strip() == sample_id]
            if batch:
                matched = matched[matched["batchNo"].astype(str).str.strip() == batch]
            for _, row in matched.iterrows():
                candidates.append({key: str(value) for key, value in row.to_dict().items()})
        if not candidates:
            return None
        candidates.sort(key=lambda row: (row.get("batchNo", ""), row.get("_samplelist_file", "")), reverse=True)
        return candidates[0]


@dataclass(frozen=True)
class FastqLocation:
    ready: bool
    ready_flag: str
    fastq_dir: str
    basecount_file: str
    r1: str
    r2: str


def locate_fastq(
    sample_row: Dict[str, str],
    sample_id: str,
    fastq_root: Path | str,
    basecount_dir: Path | str,
    ready_flag_name: str,
) -> FastqLocation:
    batch = sample_row.get("batchNo", "").strip()
    root = Path(fastq_root).expanduser()
    flag_matches = sorted(root.glob(f"*{batch}_*[0-9A-Z]/{ready_flag_name}")) if batch else []
    flag = flag_matches[0] if flag_matches else None
    fastq_dir = flag.parent if flag else Path("")
    platform = "T7" if sample_row.get("techPlatformCode", "") == "T7" else "Nova"
    basecount_file = Path(basecount_dir).expanduser() / f"{platform}_{fastq_dir.name}.basecount.txt" if flag else Path("")
    data_id = f"{sample_id}-WGS"
    r1 = fastq_dir / f"{data_id}.R1.fq.gz" if flag else Path("")
    r2 = fastq_dir / f"{data_id}.R2.fq.gz" if flag else Path("")
    return FastqLocation(
        ready=bool(flag),
        ready_flag=str(flag or ""),
        fastq_dir=str(fastq_dir) if flag else "",
        basecount_file=str(basecount_file) if flag else "",
        r1=str(r1) if flag else "",
        r2=str(r2) if flag else "",
    )


@lru_cache(maxsize=None)
def _read_basecount_frame(source: str) -> pd.DataFrame:
    with Path(source).open("r", encoding="utf-8-sig") as handle:
        header = handle.readline().rstrip("\r\n").split("\t")
        rows = []
        add_rows = 0
        for line_number, line in enumerate(handle, start=2):
            fields = line.rstrip("\r\n").split("\t")
            if len(fields) == len(header) + 1 and fields[-1].strip().casefold() == "add":
                fields = fields[:len(header)]
                add_rows += 1
            if len(fields) != len(header):
                print(
                    f"提示：basecount 文件第 {line_number} 行格式异常，已跳过：{source}；"
                    f"期望 {len(header)} 列，实际 {len(fields)} 列"
                )
                continue
            rows.append(dict(zip(header, fields)))
    if add_rows:
        print(f"提示：basecount 文件检测到 {add_rows} 行无表头 add 标记，已忽略 add 列并保留数据：{source}")
    return pd.DataFrame(rows, columns=header).fillna("")


def read_basecount(path: Path | str, sample_data_id: str) -> tuple[float | None, str]:
    source = Path(path)
    if not source.is_file():
        return None, "basecount_missing"
    frame = _read_basecount_frame(str(source.resolve()))
    if "#Sample_ID" not in frame.columns or "raw_base" not in frame.columns:
        return None, "basecount_parse_error"
    matched = frame[frame["#Sample_ID"].astype(str).str.strip() == sample_data_id]
    if matched.empty:
        return None, "sample_not_in_basecount"
    try:
        return float(matched.iloc[0]["raw_base"]), ""
    except (TypeError, ValueError):
        return None, "basecount_parse_error"
