software-deployment-method: apptainer
apptainer-args: --cleanenv --bind /bi/biodevrwbi/33.chenjiucheng/project/wgs-3.9.2-sif:/bi/biodevrwbi/33.chenjiucheng/project/wgs-3.9.2-sif:ro,/bi/BioCodeHub/WGS/WGS_V3.2.1:/bi/BioCodeHub/WGS/WGS_V3.2.1:ro,/bi/fastq/T7_Fastq:/bi/fastq/T7_Fastq:ro,/bi/software/mamba/envs/VEP/share/ensembl-vep-113.4-0/vep-data:/bi/software/mamba/envs/VEP/share/ensembl-vep-113.4-0/vep-data:ro,/bi/software/ensembl-vep-104/ensembl-vep:/bi/software/ensembl-vep-104/ensembl-vep:ro,/bi/software/scramble/cluster_analysis/resources:/bi/software/scramble/cluster_analysis/resources:ro,/bi/software/Sentieon/Zhejiang_Biosan_Biotechnology_Co._LTD_cluster.lic:/bi/software/Sentieon/Zhejiang_Biosan_Biotechnology_Co._LTD_cluster.lic:ro,/bi/6.zhangran/software/AnnotSV/share/AnnotSV:/bi/6.zhangran/software/AnnotSV/share/AnnotSV:ro,/bi/6.zhangran/software/AutoMap:/bi/6.zhangran/software/AutoMap:ro,/bi/software/slivar-0.2.4:/bi/software/slivar-0.2.4:ro
latency-wait: 120
printshellcmds: true
show-failed-logs: true
rerun-incomplete: true
executor: cluster-generic
jobs: 24
cluster-generic-submit-cmd: qsub -terse -cwd -V -l vf={resources.mem_mb}M,s_core={threads}
cluster-generic-status-cmd: qstat -j {jobid}
cluster-generic-cancel-cmd: qdel {jobid}
set-threads:
  CNV_CNV_VAF_plot: 8
  CNV_CNVall: 1
  CNV_CNVannotation: 16
  CNV_GCcorrect: 4
  CNV_annotate_chrom_CN: 1
  CNV_call_sample: 8
  CNV_correlation: 1
  CNV_fastqCount: 4
  CNV_finalize: 16
  CNV_formatCNV: 8
  CNV_getCopyNumber: 1
  CNV_insertplot: 2
  CNV_mergeCNV: 1
  CNV_pasteCopyNumber: 1
  CNV_prepare: 4
  CNV_publish: 16
  CS_CS_flt_modifier: 8
  CS_CSall: 1
  CS_createCSfile: 1
  CS_fam_SNVannotation_lenient_CS: 4
  CS_fam_SNVannotation_strict_CS: 4
  CS_fam_slivar_lenient_CS: 1
  CS_fam_slivar_strict_CS: 1
  CS_fam_split_lenient_CS: 1
  CS_fam_split_lenient_CS_correct: 8
  CS_fam_split_strict_CS: 1
  CS_fam_split_strict_CS_correct: 8
  CS_makecsvcf: 1
  CS_makecsvcf_flt: 1
  CS_markCS: 1
  CS_markCS_flt: 1
  CS_cs_normal_rawflt_to_flt: 1
  CS_cs_verbose_replace_flt: 1
  MEI_MEI: 4
  MEI_MEI_annotation: 4
  MEI_MEI_vep: 16
  MEI_MEIall: 1
  MT_MTall: 1
  MT_NorVcf: 4
  MT_mergeMTQC: 1
  MT_mityCallflt: 1
  MT_mityreport: 1
  MT_mtAnnot: 1
  MT_mtCombine: 1
  MT_mtFlt: 1
  QC_PeddyC: 4
  QC_QCall: 1
  QC_SingleQC_merge: 1
  QC_gender: 1
  QC_mergeQC: 4
  QC_multiqc_qc: 1
  QC_plotQC: 4
  QC_sceVCF: 1
  RE_REall: 1
  RE_expansionhunter: 1
  ROH_MIE: 1
  ROH_MIE_ROH_plot: 2
  ROH_ROHall: 1
  ROH_ROHcalling: 1
  ROH_format: 1
  ROH_imprintRegionR: 1
  ROH_vafplot: 2
  SMA_CYP2D6: 16
  SMA_SLC25A13: 8
  SMA_SMA: 16
  SMA_SMAall: 1
  SNV_GVCFtyper: 8
  SNV_NormalizeVcf: 16
  SNV_SNVall: 1
  SNV_batchVcf2Vaf: 8
  SNV_bedGraphVaf: 8
  SNV_blacklistFlt: 8
  SNV_createPed: 1
  SNV_fam_SNVannotation_lenient: 4
  SNV_fam_SNVannotation_strict: 4
  SNV_fam_flt_modifier: 8
  SNV_fam_normal_rawflt_to_flt: 1
  SNV_fam_slivar_lenient: 1
  SNV_fam_slivar_strict: 1
  SNV_fam_split_lenient: 1
  SNV_fam_split_lenient_correct: 8
  SNV_fam_split_strict: 1
  SNV_fam_split_strict_correct: 8
  SNV_fam_verbose_replace_flt: 1
  SNV_intergenicFlt: 16
  SNV_qualityFlt: 16
  SNV_regionFlt: 8
  SNV_select_4tiers: 8
  SNV_solo_SNVannotation_lenient: 4
  SNV_solo_SNVannotation_strict: 4
  SNV_solo_flt_modifier: 8
  SNV_solo_normal_rawflt_to_flt: 1
  SNV_solo_split_lenient: 1
  SNV_solo_split_strict: 1
  SNV_solo_verbose_replace_flt: 1
  SNV_splitVcf: 8
  SNV_trio_split: 1
  SNV_vcfTag: 8
  SNV_vcfTagCandidateOther: 8
  SNV_vep: 16
  SNV_vepPosCorr: 16
  SNV_virtualWES: 16
  SV_SVall: 1
  SV_SVsort: 1
  SV_SVtsv: 16
  SV_splitCNV: 16
  SV_svVep: 16
  pre_process_Dedup: 64
  pre_process_Haplotyper: 64
  pre_process_MEICall: 1
  pre_process_Preall: 1
  pre_process_QCStatic: 32
  pre_process_QCStaticPlot: 1
  pre_process_QualCal: 64
  pre_process_SentieonQCCram: 32
  pre_process_Smooverun: 16
  pre_process_bam2blockUniq: 32
  pre_process_cleanFastq: 16
  pre_process_mapping: 64
  pre_process_mityCall: 1
  pre_process_mtQC: 4
set-resources:
  CNV_CNV_VAF_plot:
    mem_mb: 12288
  CNV_CNVall:
    mem_mb: 512
  CNV_CNVannotation:
    mem_mb: 32768
  CNV_GCcorrect:
    mem_mb: 16384
  CNV_annotate_chrom_CN:
    mem_mb: 4096
  CNV_call_sample:
    mem_mb: 32768
  CNV_correlation:
    mem_mb: 4096
  CNV_fastqCount:
    mem_mb: 16384
  CNV_finalize:
    mem_mb: 65536
  CNV_formatCNV:
    mem_mb: 32768
  CNV_getCopyNumber:
    mem_mb: 4096
  CNV_insertplot:
    mem_mb: 12288
  CNV_mergeCNV:
    mem_mb: 4096
  CNV_pasteCopyNumber:
    mem_mb: 4096
  CNV_prepare:
    mem_mb: 16384
  CNV_publish:
    mem_mb: 65536
  CS_CS_flt_modifier:
    mem_mb: 12000
  CS_CSall:
    mem_mb: 512
  CS_createCSfile:
    mem_mb: 20480
  CS_fam_SNVannotation_lenient_CS:
    mem_mb: 20480
  CS_fam_SNVannotation_strict_CS:
    mem_mb: 20480
  CS_fam_slivar_lenient_CS:
    mem_mb: 20480
  CS_fam_slivar_strict_CS:
    mem_mb: 20480
  CS_fam_split_lenient_CS:
    mem_mb: 20480
  CS_fam_split_lenient_CS_correct:
    mem_mb: 20480
  CS_fam_split_strict_CS:
    mem_mb: 20480
  CS_fam_split_strict_CS_correct:
    mem_mb: 20480
  CS_makecsvcf:
    mem_mb: 20480
  CS_makecsvcf_flt:
    mem_mb: 20480
  CS_markCS:
    mem_mb: 20480
  CS_markCS_flt:
    mem_mb: 20480
  CS_cs_normal_rawflt_to_flt:
    mem_mb: 10000
  CS_cs_verbose_replace_flt:
    mem_mb: 10000
  MEI_MEI:
    mem_mb: 12288
  MEI_MEI_annotation:
    mem_mb: 20480
  MEI_MEI_vep:
    mem_mb: 32768
  MEI_MEIall:
    mem_mb: 512
  MT_MTall:
    mem_mb: 512
  MT_NorVcf:
    mem_mb: 10000
  MT_mergeMTQC:
    mem_mb: 2048
  MT_mityCallflt:
    mem_mb: 20480
  MT_mityreport:
    mem_mb: 20480
  MT_mtAnnot:
    mem_mb: 20480
  MT_mtCombine:
    mem_mb: 10000
  MT_mtFlt:
    mem_mb: 20480
  QC_PeddyC:
    mem_mb: 10240
  QC_QCall:
    mem_mb: 512
  QC_SingleQC_merge:
    mem_mb: 10240
  QC_gender:
    mem_mb: 4096
  QC_mergeQC:
    mem_mb: 20480
  QC_multiqc_qc:
    mem_mb: 4096
  QC_plotQC:
    mem_mb: 20480
  QC_sceVCF:
    mem_mb: 4096
  RE_REall:
    mem_mb: 512
  RE_expansionhunter:
    mem_mb: 30720
  ROH_MIE:
    mem_mb: 4096
  ROH_MIE_ROH_plot:
    mem_mb: 12288
  ROH_ROHall:
    mem_mb: 512
  ROH_ROHcalling:
    mem_mb: 10240
  ROH_format:
    mem_mb: 4096
  ROH_imprintRegionR:
    mem_mb: 4096
  ROH_vafplot:
    mem_mb: 12288
  SMA_CYP2D6:
    mem_mb: 20480
  SMA_SLC25A13:
    mem_mb: 20480
  SMA_SMA:
    mem_mb: 20480
  SMA_SMAall:
    mem_mb: 512
  SNV_GVCFtyper:
    mem_mb: 10000
  SNV_NormalizeVcf:
    mem_mb: 32768
  SNV_SNVall:
    mem_mb: 512
  SNV_batchVcf2Vaf:
    mem_mb: 20480
  SNV_bedGraphVaf:
    mem_mb: 20480
  SNV_blacklistFlt:
    mem_mb: 10000
  SNV_createPed:
    mem_mb: 2048
  SNV_fam_SNVannotation_lenient:
    mem_mb: 10000
  SNV_fam_SNVannotation_strict:
    mem_mb: 10000
  SNV_fam_flt_modifier:
    mem_mb: 12000
  SNV_fam_normal_rawflt_to_flt:
    mem_mb: 10000
  SNV_fam_slivar_lenient:
    mem_mb: 10000
  SNV_fam_slivar_strict:
    mem_mb: 10000
  SNV_fam_split_lenient:
    mem_mb: 10000
  SNV_fam_split_lenient_correct:
    mem_mb: 20000
  SNV_fam_split_strict:
    mem_mb: 10000
  SNV_fam_split_strict_correct:
    mem_mb: 20000
  SNV_fam_verbose_replace_flt:
    mem_mb: 10000
  SNV_intergenicFlt:
    mem_mb: 32768
  SNV_qualityFlt:
    mem_mb: 32768
  SNV_regionFlt:
    mem_mb: 10000
  SNV_select_4tiers:
    mem_mb: 12000
  SNV_solo_SNVannotation_lenient:
    mem_mb: 10000
  SNV_solo_SNVannotation_strict:
    mem_mb: 10000
  SNV_solo_flt_modifier:
    mem_mb: 12000
  SNV_solo_normal_rawflt_to_flt:
    mem_mb: 10000
  SNV_solo_split_lenient:
    mem_mb: 10000
  SNV_solo_split_strict:
    mem_mb: 10000
  SNV_solo_verbose_replace_flt:
    mem_mb: 10000
  SNV_splitVcf:
    mem_mb: 20480
  SNV_trio_split:
    mem_mb: 10000
  SNV_vcfTag:
    mem_mb: 12000
  SNV_vcfTagCandidateOther:
    mem_mb: 12000
  SNV_vep:
    mem_mb: 32768
  SNV_vepPosCorr:
    mem_mb: 10000
  SNV_virtualWES:
    mem_mb: 32768
  SV_SVall:
    mem_mb: 512
  SV_SVsort:
    mem_mb: 10240
  SV_SVtsv:
    mem_mb: 32768
  SV_splitCNV:
    mem_mb: 32768
  SV_svVep:
    mem_mb: 32768
  pre_process_Dedup:
    mem_mb: 131072
  pre_process_Haplotyper:
    mem_mb: 131072
  pre_process_MEICall:
    mem_mb: 10000
  pre_process_Preall:
    mem_mb: 512
  pre_process_QCStatic:
    mem_mb: 65536
  pre_process_QCStaticPlot:
    mem_mb: 20480
  pre_process_QualCal:
    mem_mb: 131072
  pre_process_SentieonQCCram:
    mem_mb: 65536
  pre_process_Smooverun:
    mem_mb: 32768
  pre_process_bam2blockUniq:
    mem_mb: 65536
  pre_process_cleanFastq:
    mem_mb: 32768
  pre_process_mapping:
    mem_mb: 131072
  pre_process_mityCall:
    mem_mb: 20480
  pre_process_mtQC:
    mem_mb: 20480
