schema_version: "4"
current_release_id: wgs-4.2.0-b067c72
releases:
  - release_id: wgs-4.2.0-b067c72
    version: V4.2.0
    source_commit: b067c72eed795e59b724b13324b0d380ae8b7e94
    bs10610_repo_path: /mnt/biodevrwbi/33.chenjiucheng/project/wgs-4.2.0
    node200_repo_path: /bi/biodevrwbi/33.chenjiucheng/project/wgs-4.2.0
    rule_event_schema_version: "1"
    profile_id: wgs-4.2.0
    profile_revision: r1
    profile_sha256: 2e7087a6ba646dfb67a940cd77d27ad18fc99e32d92c0ee5243614416f71f38b
    node200_profile_path: /bi/biodevrwbi/33.chenjiucheng/project/cce-pipeline-profiles/wgs/wgs-4.2.0-r1.yaml
    cce_pipeline_version: 0.8.3
    pipeline_build_sha256: 71695b2a3ab1d83bab68454b1785d2b6791b26c6f57f5ecceda465975788b7f6
    resource_manifest_sha256: 89ea682efe61f6a0202c41b01cdc10de2355dcc496834a61513d357d86a2b049
  - release_id: wgs-4.1.1-6c98281
    version: V4.1.1
    source_commit: 6c982817614db6a1157b6f287427ddf01ac91827
    bs10610_repo_path: /mnt/biodevrwbi/33.chenjiucheng/project/wgs-4.1.1
    node200_repo_path: /bi/biodevrwbi/33.chenjiucheng/project/wgs-4.1.1
    rule_event_schema_version: "1"
  - release_id: wgs-4.1.1-2499749
    version: V4.1.1
    source_commit: 2499749ce7fd200d4269d1ee03d7b6a4e8d5bb68
    bs10610_repo_path: /mnt/biodevrwbi/33.chenjiucheng/project/wgs-4.1.1
    node200_repo_path: /bi/biodevrwbi/33.chenjiucheng/project/wgs-4.1.1
    rule_event_schema_version: "1"
  - release_id: wgs-4.1.1-cdee32c
    version: V4.1.1
    source_commit: cdee32c9d3c689f4af6ea8a0f7a8296f79c10a1d
    bs10610_repo_path: /mnt/biodevrwbi/33.chenjiucheng/project/wgs-4.1.1
    node200_repo_path: /bi/biodevrwbi/33.chenjiucheng/project/wgs-4.1.1
    rule_event_schema_version: "1"
  - release_id: wgs-4.1.1-1656b5d
    version: V4.1.1
    source_commit: 1656b5d7a6e2f24242c38149f6d1c92ac266cd37
    bs10610_repo_path: /mnt/biodevrwbi/33.chenjiucheng/project/wgs-4.1.1
    node200_repo_path: /bi/biodevrwbi/33.chenjiucheng/project/wgs-4.1.1
    rule_event_schema_version: "1"
  - release_id: wgs-4.1.1-1778fca
    version: V4.1.1
    source_commit: 1778fcabd99b5253aa90cd410112dc2f78e0c51a
    bs10610_repo_path: /mnt/biodevrwbi/33.chenjiucheng/project/wgs-4.1.1
    node200_repo_path: /bi/biodevrwbi/33.chenjiucheng/project/wgs-4.1.1
    rule_event_schema_version: "1"
